# Generated by Django 5.1.1 on 2024-09-09 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journeys', '0002_train'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainjourney',
            name='train_name',
        ),
    ]
